[package]
name = "bxolotl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = { version = "0.10" }
hmac = { version = "0.12.1" }
ring = { version = "0.16" }